apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculator-dev-app
  namespace: argocd
spec:
  project: calculator-project
  source:
    repoURL: https://github.com/stevymonkam/gitops-java-kustumize-argocd.git
    targetRevision: main
    path: apps/frontend/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true